# Generated by Django 2.1.7 on 2019-07-11 14:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
