# Generated by Django 2.1.7 on 2019-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0003_auto_20190319_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentform',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
