# Generated by Django 2.1.7 on 2019-06-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0004_auto_20190429_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
