# Generated by Django 2.1.7 on 2019-06-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0007_deteils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deteils',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.student'),
        ),
    ]
