# Generated by Django 2.1.7 on 2019-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
